import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Hello': 'Hello',
          'Alakhwan': 'Alakhwan',
          'Home_Page': ' Home Page ',
          'My_Wallet': ' My Wallet',
          'Notifications': 'Notifications ',
          'Contact_Us': 'Contact Us ',
          'Update_profile': 'Update profile',
          "Updated_Successfully": "Updated Successfully",
          'MyProfile': 'Profile Page',
          'No_Image_selected': 'No Image selected',
          'Logout': 'Logout ',
          'Search_Lawyer': 'Search Lawyer',
          "All_Bookings": "All Bookings",
          'About_Us': 'About Us',
          'Next_Appointment': 'Next Appointment',
          'Lawyer': 'Lawyer',
          'About_Lawyer': 'About Lawyer',
          'Top_Lawyer': 'Top Lawyer',
          'See_All': 'See All',
          'About_Me': 'About Me',
          'abou_rak':
              'Ras Al Khaimah Law Firm is one of the leading legal institutions in the United Arab Emirates, where the Ras Al Khaimah Law Firm has a group of lawyers, who have great legal and practical skills, based on their long experience in the field of law and legal advice, which formed our effective professional strategy to achieve the best office A lawyer who can stand out in providing all legal services and litigation in Dubai and the United Arab Emirates with high professionalism and expertise.',
          'Legal_Advance': "Legal \nAdvance",
          "payment_transactions": "Payment Transactions",
          "payment transactions": "payment \ntransactions",
          'Fee': 'Fee',
          'AED': 'AED',
          'Experiences': 'Experiences',
          'Rating': 'Rating',
          'Years': 'Years',
          'Book_Appointment': 'Book Appointment',
          'Schedule': 'Schedule',
          'Reschedule': 'Reschedule',
          'Up_Coming': 'Up Coming',
          'Complete': 'Complete',
          'Cancle': 'Cancel',
          'Delete': 'Delete',
          'OK': 'OK',
          'Rescheduled': 'Rescheduled',
          "Total": 'Total',
          'Name': 'Name',
          'Enter_name': 'Enter your user name',
          'Enter': 'Enter',
          'Phone': 'Phone',
          'Email': 'Email',
          'Verifying_Email': "Verifying Email",
          'veri_email_resend_successfully':
              'The verification email has been successfully resent',
          'resend': 'Resend',
          'Check_your_Email':
              'Check your Email We have Sent you a Verification Email',
          'field_required': 'This field is required',
          'Go_to_login': 'Go to login',
          'Login': 'Login',
          'Register': 'Register',
          'We_will_email':
              'We will email you a verification code to check your authenticity.',
          'Password_length': 'Password must be at least 8 characters in length',
          'Remember_password': 'Remember your password? ',
          'Details': 'Details',
          'Send': 'Send',
          'User_Name': 'User Name',
          'Password': 'Password',
          'Forgot_password': 'Forgot your password?',
          'Enter_email_associated_account':
              'Enter the email address associated with your account.',
          'didn_receive_code': "If you didn't receive a code! ",
          'Dont_have_account': 'Don\'t have an account? ',
          'not_valid_email_address': 'Enter a valid email address',
          'Sign_In': 'Sign In',
          'Signin_your_account': 'Signin into your account',
          'Create': 'Create',
          'Location': 'Location',
          'hint_text': 'You have pushed the button this many times',
          'Language': 'Change language',
          'increment': 'Increment',
          'Alert': 'Alert',
          'sure_want_exit': 'Are you sure you want to exit?',
          'Successfully_Done': 'Successfully Done',
          'email_sent_successfully':
              'The email has been sent successfully. Please review your email',
          'Email_notVerifyed':
              'Your Email is not Verifyed please Verifyed your Email and Try Again',
          "can_not_empty": "Field can't be empty",
          'No_Internet': 'No Internet Connection Available',
          'No_Appointment': 'There Are No Appointment Yet',
          'NO': 'NO',
          'YES': 'YES',
          'Online': 'Online',
          'Office': 'Office',
          'Enter_Date': 'Enter Date',
          'Enter_Time': 'Enter Time',
          'Time&Date': 'Time & Date',
          'Booking_Steps': 'Booking Steps',
          'When_date': 'When do you want the date to be ?',
          'Input_Start_Date': 'Please Input Start Date',
          'Time_is_not_selected': 'Time Is Not Selected',
          'not_selected': 'Not Selected',
          "change_choices?": 'Do you want to change one of your choices?',
          'Where_appointment?': 'Where do you want the appointment to be ?',
          'Pay': 'Pay',
          'Continue': 'Continue',
          "Location_Not_Selected": "Location Not Selected",
          "Please_Select_Location": "Please Select Location",
          "About_consultation": "About Consultation",
          "choose_other_mentioned":
              "The consultation lasts 1 hour with the specialized consultant, and the consultation takes place in the periods mentioned below. \n In the event that the consultation is in a period other than mentioned, the price varies.",
          "Available_working_hours":
              "Available working hours are : \nSaturday to Thursday \n8 - 2 AM || 5 - 9 PM,\n Sunday 9 - 1 AM || 5-9 PM.\n Friday 8 - 12 AM.",
          "Provisions": "Provisions",
          'Documentation_contracts': 'Documentation \nand contracts',
          "Date_Not_Selected": "Date or Time Not Selected",
          "Please_Select_Date": "Please Select Date and Time",
          'Sunday': "Sunday",
          'Monday': "Monday",
          'Thursday': "Thursday",
          'Friday': "Friday",
          'Saturday': "Saturday",
          "AM": "AM",
          "PM": "PM",
          "Working_days": "Working Days",
          "morning_shift": "Morning Shift",
          "evening_shift": "Evening Shift",
          "Choose_Language": "Choose Your Preferred Language",
          "Skip": "Skip",
          "chat": 'Chat',
          "agree_terms_conditions": "I agree to the terms and conditions",
          "must_agree": "You must agree to the terms and conditions",
          "Top categories": "Top categories",
          "All_purchases": "All purchases",
          "Favorites": "Favorites",
          "Search": "Search"
        },
        'ar_SA': {
          'Hello': 'مرحبا بك',
          'Alakhwan': 'الأخوان',
          'Home_Page': 'الصفحة الرئيسية',
          'My_Wallet': 'المحفظة ',
          'Notifications': 'الأشعارات',
          'Contact_Us': 'تواصل معنا',
          'MyProfile': 'الصفحة الشخصية',
          'No_Image_selected': 'لم يتم تحديد أي صورة',
          'Update_profile': 'تعديل الصفحة الشخصية',
          "Updated_Successfully": 'تم التعديل بنجاح',
          'Logout': 'تسجيل خروج',
          'Search_Lawyer': 'ابحث عن محامي',
          'Lawyer': 'محامي',
          'Next_Appointment': "الموعد التالي",
          'Top_Lawyer': 'أفضل المحامين',
          'See_All': 'اظهار الكل',
          'About_Lawyer': 'عن المحامي',
          'abou_rak':
              'مكتب  رأس الخيمة للمحاماة من المؤسسات القانونية الرائدة في دولة الامارات العربية المتحدة، حيث يمتلك مكتب رأس الخيمة للمحاماة مجموعة من المحامين، الذين يتمتعون بالمهارات القانونية والعملية  الكبيرة وذلك من واقع خبراتهم الطويلة في مجال المحاماه والإستشارات القانونية، الأمر شكل لدينا استراتيجيتنا المهنية الفاعلة لتحقيق افضل مكتب محاماه يمكن له البروز في تقديم كافة الخدمات القانونية والتقاضي في دبي والامارات العربية المتحدة بمهنية واحترافية عالية.',
          'Legal_Advance': "نصائح قانونية ",
          'Fee': 'السعر',
          "payment_transactions": "معاملات الدفع",
          "payment transactions": "معاملات الدفع",
          'AED': 'درهم',
          'Experiences': 'الخبرة',
          'Rating': 'التقييم',
          'Years': 'سنة',
          'Book_Appointment': 'حجز موعد',
          "All_Bookings": "كل الحجوزات",
          'About_Us': 'عنا',
          'Schedule': 'الجدولة',
          'Reschedule': 'اعادة جدولة',
          'Rescheduled': 'معاد جدولتها',
          'Up_Coming': 'قادمة',
          'Complete': 'مكتملة',
          'Cancle': 'الغاء',
          'Cancled': 'ملغاة',
          'Delete': 'حذف',
          'OK': 'موافق',
          'Total': 'المجموع',
          'Name': 'الاسم',
          'Enter_name': 'ادخل اسم المستخدم',
          'Phone': 'الهاتف',
          'Email': 'البريد الالكتروني',
          'Verifying_Email': " تحقق من البريد الإلكتروني",
          'veri_email_resend_successfully': 'تم إعادة إرسال رسالة التحقق بنجاح',
          'Check_your_Email':
              'تحقق من بريدك الإلكتروني لقد أرسلنا لك رسالة للتحقق',
          'resend': 'اعادة ارسال',
          'didn_receive_code': ' إذا لم تتلق رمز التحقق!',
          'Password_length': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
          'Remember_password': 'تذكرت كلمة المرور ? ',
          "can_not_empty": 'لا يمكن أن يكون الحقل فارغًا',
          'Details': 'التفاصيل',
          'Send': 'ارسال',
          'Location': 'الموقع',
          'User_Name': 'اسم المستخدم',
          'Password': 'كلمة المرور',
          'Forgot_password': 'نسيت كلمة السر؟',
          'not_valid_email_address': 'أدخل عنوان بريد إلكتروني صالح',
          'Enter_email_associated_account':
              'أدخل عنوان البريد الإلكتروني المرتبط بحسابك.',
          'We_will_email':
              'سنرسل لك رمز التحقق عبر البريد الإلكتروني للتحقق من صحته.',
          'field_required': "هذا الحقل مطلوب",
          'Dont_have_account': 'ليس لديك حساب ? ',
          'Create': 'انشاء',
          'Go_to_login': 'الذهاب الي تسجيل الدخول',
          'Login': 'تسجيل دخول',
          'Register': 'تسجيل حساب',
          'Sign_In': 'تسجيل الدخول',
          'Signin_your_account': 'تسجيل الدخول إلى حسابك',
          'hint_text': 'لقد ضغطت على الزر عدة مرات',
          'Language': 'تغير اللغة',
          'increment': 'زيادة راتب',
          'Alert': 'تحذير',
          'sure_want_exit': 'هل أنت متأكد أنك تريد الخروج؟',
          'Successfully_Done': 'تمت بنجاح',
          'email_sent_successfully':
              'تم إرسال البريد الإلكتروني بنجاح. يرجى مراجعة البريد الإلكتروني الخاص بك',
          'schedule_appointment_contact': 'سوف نقوم بجدوله موعد والتواصل معك',
          'Email_notVerifyed':
              'لم يتم التحقق من بريدك الإلكتروني ، يرجى التحقق من بريدك الإلكتروني والمحاولة مرة أخرى .',
          'No_Internet': 'لا يوجد اتصال  بالأنترنت',
          'No_Appointment': 'لا يوجد حجز حتى الآن',
          'NO': 'لا',
          'YES': 'نعم',
          'Online': 'الكترونية',
          'Office': 'في المكتب',
          'Enter_Date': 'ادخل التاريخ',
          'Enter_Time': 'ادخل الذمن',
          'Enter': 'دخول',
          'Time&Date': 'التاريخ والوقت',
          'Booking_Steps': 'خطوات الحجز',
          'When_date': 'متى تريد أن يكون التاريخ؟',
          'Input_Start_Date': 'الرجاء إدخال تاريخ البدء',
          'Time_is_not_selected': 'لم يتم تحديد الوقت',
          'not_selected': 'لم يتم الاختيار',
          "change_choices?": 'هل تريد تغيير أحد اختياراتك؟',
          'Where_appointment?': 'أين تريد أن يكون الموعد؟',
          'Pay': 'ادفع',
          'Continue': 'متابعة',
          "Location_Not_Selected": "الموقع غير محدد",
          "Please_Select_Location": "يرجى تحديد الموقع",
          "Available_working_hours":
              "ساعات العمل المتاحة هي: \n من السبت إلى الخميس \n8 - 2 صباحًا || 5 - 9 مساءً ، \n الأحد 9 - 1 صباحًا || من 5 إلى 9 مساءً. \n الجمعة 8 - 12 صباحًا.",
          "choose_other_mentioned":
              "الاستشارة مدتها 1 ساعة مع المستشار المختص وتكون الاستشارة في الفترات المذكورة ادناه.\n.وفي حال كانت الاستشارة في فترة غير المذكورة يفرق السعر",
          "Provisions": "أحكام",
          "About_consultation": "عن الاستشارة",
          'Documentation_contracts': 'الوثائق والعقود',
          "Date_Not_Selected": "التاريخ أو الوقت غير محدد",
          "Please_Select_Date": "يرجى تحديد التاريخ والوقت",
          'Sunday': "الأحد",
          'Monday': "الإثنين",
          'Thursday': "الخميس",
          'Friday': "الجمعة",
          'Saturday': "السبت",
          "AM": "ص",
          "PM": "م",
          "Working_days": "أيام العمل",
          "morning_shift": "وردية الصباح",
          "evening_shift": "وردية المساء",
          "Choose_Language": "اختر اللغة المفضلة لديك",
          "Skip": "تخطي",
          "chat": "محادثة",
          "agree_terms_conditions": "اوافق علي الشروط والاحكام",
          "must_agree": "يجب ان توافق علي الشروط والاحكام",
          "Top categories": "أعلى الفئات",
          "All_purchases": "كل المشتريات",
          "Favorites": "المفضلة",
          "Search": "ابحث"
        }
      };
}
